services:
  mvcapp01:
    build: .
    ports:
      - "9999:80"
    environment:
      - ASPNETCORE_URLS=http://*:80
    depends_on:
      -   sql01:
  sql01:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Deneme123456!"
    ports:
      - 8585:1433